const SECONDS_IN_A_MINUTE = 60;
const SECONDS_IN_AN_HOUR = SECONDS_IN_A_MINUTE * 60;
const SECONDS_IN_A_DAY = SECONDS_IN_AN_HOUR * 24;

export const ACCESS_TOKEN_EXP = SECONDS_IN_A_MINUTE * 15;
export const REFRESH_TOKEN_EXP = SECONDS_IN_A_DAY * 7;
